apiVersion: apps/v1
kind: Deployment
metadata:
  name: taska3-phpload
spec:
  selector:
    matchLabels:
      run: taska3-phpload
  replicas: 1
  template:
    metadata:
      labels:
        run: taska3-phpload
    spec:
      containers:
      - name: taska3-phpload
        image: taska3-phpload
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: taska3-phpload
  labels:
    run: taska3-phpload
spec:
  ports:
  - port: 80
  selector:
    run: taska3-phpload
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: taska3-phpload
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taska3-phpload
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
