FROM nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./index.html /usr/share/nginx/html/rp/index.html
COPY ./test.html /usr/share/nginx/test/index.html
COPY ./test1.html /usr/share/nginx/test1/index.html
ADD images /usr/share/nginx/images